import { SyntheticEvent } from "react";
import { ListDetail } from '../components/ListDetail';

export interface ContainerInterface  {
    children:  React.ReactElement 
}
export interface breadcrumbInterface {
    breadcrumb : breadcrumb[],
    titulo?: String,
    mensaje?: String
}
export interface Breadcrumb {
    id:number;
    titulo: string;
    enlace: string;
}
export interface ContainerInner{
    children: React.ReactElement,
    breadcrumb : breadcrumb[],
    titulo?:string,
}
export interface PersonalForm{
    category?: string;
    page: string;
    tipo?: number
}
export interface PersonalList{
    category?:string;
    page:string;
    tipo?: number;
}
export interface TablalList{
    children: React.ReactElement,
    category?:string,
    page:string,
    cabecera: string[],
    detalle:listaDetalle[],    
    eliminar: Function,
    next: Function,
    prev: Function
}
export interface ReportList{
    children: React.ReactElement,
    cabecera: string[],
    detalle:listaDetalle[],    
    descargar: Function,
    next: Function,
    prev: Function
}

export interface SaveList{
    children: React.ReactElement,
    cabecera: string[],
    detalle:listaDetalle[],    
    editar: Function,
    eliminar: Function
}

export interface paginationInterface extends SyntheticEvent {   
}
export interface MenuInterface {
    nombre: string;
    alias:  string;
    icono:  string;
}
export interface AccessInterface{
    Menu: MenuInterface[]
}
export interface ControlsInterface{
    tipo?: 'new' | 'edit' | 'delete' | 'list'; 
    save?: Function ;
    category?:string;
    page:string;
}
export interface ListDetail{
    cabecera: string[],
    detalle:listaDetalle[],
    eliminar: Function,
}

export interface CategoryListInterface{
    name : string,
    id:number,
    alias : string,
    children?: CategoryListInterface[]
}

export interface BuscarPersonas extends FormBuscarPersonasValues {    
    buscar:boolean
}

export interface baseArray{
    id:number,
    nombre:string
}


export interface FormPersonasValuesSave extends FormPersonasValues {
    documento_tipo : number,
    usuario_tipo : number | undefined
}

// types
export type breadcrumb = {
    id:number;
    titulo: string;
    enlace: string;
}

export type FormBuscarPersonasValues = {
    documento: string | null;
    nombres: string | null;  
    fechaCreacion: Date | null;  
};

export type FormPersonasValues = {
    documento: string | null;
    nombres: string | null;
    apellidos:string | null;
    celular:string | null;
    departamento:number | null;
    provincia:number | null;
    distrito:number | null;
    direccion:string | null;
    email?:string | null;
    password?:string | null;
};


export interface listaDetalle  {
    id: string,
    campos?: string[] | undefined   
};

// ! CRERA EL TIPADO PARA EL DETALLE DE LA NOTA DE HELADERO
export type listaDetalleNotaHeladero = {
    id: number,
    campos: string[]    
}

export type modulos = string | 'clientes' | 'heladeros' | 'personal' | 'proveedores';


/** */

// Generated by https://quicktype.io

export interface Departamentos {
    data: Departamento[];
}

export interface Departamento {
    id:           number;
    departamento: string;
    pais_id:      number;
    created_at:   null;
    updated_at:   null;
}


// Generated by https://quicktype.io

export interface Provincias {
    data: provincia[];
}

export interface provincia {
    id:              number;
    provincia:       string;
    departamento_id: number;
    ubigeo:          string;
    created_at:      null;
    updated_at:      null;
}


// Generated by https://quicktype.io

export interface Distritos {
    data: Distrito[];
}

export interface Distrito {
    id:           number;
    distrito:     string;
    provincia_id: number;
    ubigeo:       string;
    created_at:   null;
    updated_at:   null;
}
