// Generated by https://quicktype.io

export interface Facturaciones {
    data:          Facturas[];
    next_page:     null;
    previous_page: null;
}

export interface Facturas {
    id:                 number;
    codigo:             null;
    serie:              string;
    correlativo:        number;
    user_id:            number;
    tipo:               number;
    fecha_pago:         string;
    id_usuario:         number;
    created_at:         string;
    updated_at:         string;
    sucursals_id:       number;
    fecha_emision:      string;
    tipo_transaccion:   number;
    id_estado:          number;
    id_moneda:          number;
    usuario_documento:  string;
    usuario_nombre:     string;
    estado:             string;
    documento:          string;
    moneda:             string;
    monto:              string;
    total:              string;
    detalle?:          FormFacturacionDetalleValues[];
}

export interface FormFacturacionDetalleValues {
    id:          number;
    codigo?:      string;
    precio?:      number;
    descuento?:   number;
    cantidad?:    number;
    facturas_id?: number;
    producto?:    string;
    total?:      number;
}

export interface intialStateFacturas {
    status: boolean;
    facturas:Facturas[];
    nextPage: string | null;
    prevPage: string | null;
    active: Facturas | null;
    errorMessage: string | null | undefined;
}