// Generated by https://quicktype.io

export interface Facturaciones {
    data:          Facturas[];
    next_page:     null;
    previous_page: null;
}

export interface Facturas {
    id:                number;
    codigo:            null;
    serie:             string;
    correlativo:       number;
    user_id:           number;
    tipo:              number;
    fecha_pago:        string;
    id_usuario:        number;
    created_at:        string;
    updated_at:        string;
    sucursals_id:      number;
    fecha_emision:     string;
    tipo_transaccion:  number;
    id_estado:         number;
    id_moneda:         number;
    estado:            string;

    documento_tipo?:    string;
    usuario_documento?: string;
    creador?:           string;
    sucursal?:          string;
    moneda?:            string;
    transaccion?:       string;
    usuario_nombre?:    string;
    documento?:         string;
    total_monto:        number;
    total_descuento:    number;

    subtotal:           number | string;
    descuento:          number | string;
    igv:                number | string;
    total:              number | string;
    detalle?:          FormFacturacionDetalleValues[];
}

export interface FormFacturacionDetalleValues {
    id:          number;
    codigo?:      string;
    precio?:      number;
    descuento?:   number;
    cantidad?:    number;
    facturas_id?: number;
    producto?:    string;
    total?:      number | string;
}

export interface intialStateFacturas {
    status: boolean;
    facturas:Facturas[];
    nextPage: string | null;
    prevPage: string | null;
    active: Facturas | null;
    errorMessage: string | null | undefined;
}