// Generated by https://quicktype.io

export interface NotaHeladeros {
    data:          NotaHeladero[];
    next_page:     null;
    previous_page: null;
}

export interface NotaHeladero{
    codigo:                  string;
    id:                      number;
    parent_id:               number;
    user_id:                 number;
    moneda_id:               number;
    id_sucursal:             number;
    monto:                   number;
    pago:                    number;
    debe:                    number;
    deuda_anterior?:         number;
    cargo_baterias:          number;
    ahorro:                  number;
    estado?:                 any;
    idestado?:               number;
    cucharas?:               number;
    conos?:                  number;
    placas_entregas?:        number;
    placas_devueltas?:       number;
    fecha_guardado?:         Date;
    fecha_apertura?:         Date;
    fecha_cierre?:           Date;
    fecha_movimiento?:       Date;
    id_usuario?:             number;
    created_at:              Date;
    updated_at?:             Date;
    name?:                   string;
    heladero_documento?:     string;
    heladero_nombre?:        string;
    nombre?:                 string;
    estado_nombre?:          string;
    moneda?:                 string;
    observaciones?:          string;
    id_children:             number;
    detalle:                 FormNotaHeladeroDetalleValues[];
}

export interface FormNotaHeladeroDetalleValues {
    id?:                number;
    devolucion?:        number;
    devolucion_today?:  number;
    pedido?:            number;
    vendido?:           number;
    importe?:           number;
    nota_heladeros_id?: number;
    created_at?:        string;
    updated_at?:        string;
    codigo:             string;
    producto?:          string;
    precio_operacion?:  number;
    is_litro?:          boolean;
}

export interface intialStateNotaHeladero {
    status: boolean;
    Heladeros:NotaHeladero[];
    nextPage: string | null;
    prevPage: string | null;
    active: NotaHeladero | null;
    errorMessage: string | null | undefined;
}

export interface NotaIncomplete {
    data: DataNoteIncomplete[];
}

export interface DataNoteIncomplete {
    id:                 number;
    parent_id:          number;
    user_id:            number;
    moneda_id:          number;
    id_sucursal:        number;
    monto:              string;
    pago:               string;
    debe:               string;
    ahorro:             string;
    estado:             number;
    cucharas:           number;
    conos:              number;
    placas_entregas:    number;
    placas_devueltas:   number;
    fecha_guardado:     null;
    fecha_apertura:     null;
    fecha_cierre:       null;
    id_usuario:         number;
    created_at:         Date;
    updated_at:         Date;
    cucharas_devueltas: number;
    conos_devueltas:    number;
    codigo:             string;
    deuda_anterior:     number;
    cargo_baterias:     number;
    detalle:            Detalle[];
}

export interface Detalle {
    id:                    number;
    devolucion:            number;
    pedido:                number;
    vendido:               number;
    importe:               string;
    nota_heladeros_id:     number;
    created_at:            Date;
    updated_at:            Date;
    codigo:                string;
    producto:              string;
    heladero_precio_venta: string;
    heladero_descuento:    string;
    is_litro:              number;
    devolucion_today:      null;
    stock_alert_input:     string;
    cantidad_caja:         number;
}
