// Generated by https://quicktype.io

export interface NotaHeladeros {
    data:          NotaHeladero[];
    next_page:     null;
    previous_page: null;
}

export interface NotaHeladero{
    id:                      number;
    user_id:                 number;
    moneda_id:               number;
    id_sucursal:             number;
    monto?:                  string;
    pago?:                   string;
    debe?:                   string;
    ahorro?:                 string;
    estado?:                 any;
    cucharas?:               number;
    conos?:                  number;
    placas_entregas?:        number;
    placas_devueltas?:       number;
    fecha_guardado?:         Date;
    fecha_apertura?:         Date;
    fecha_cierre?:           Date;
    fecha_movimiento?:       Date;
    id_usuario?:             number;
    created_at:              Date;
    updated_at?:             Date;
    name?:                   string;
    heladero_documento?:     string;
    heladero_nombre?:        string;
    nombre?:                 string;
    detalle:                 FormNotaHeladeroDetalleValues[];
}

export interface FormNotaHeladeroDetalleValues {
    id?:                number;
    devolucion?:        number;
    pedido?:            number;
    vendido?:           number;
    importe?:           string;
    nota_heladeros_id?: number;
    created_at?:        string;
    updated_at?:        string;
    codigo?:            string;
    producto?:          string;
}

export interface intialStateNotaHeladero {
    status: boolean;
    notaHeladero:NotaHeladero[];
    nextPage: string | null;
    prevPage: string | null;
    active: NotaHeladero | null;
    errorMessage: string | null | undefined;
}

