// Generated by https://quicktype.io

export interface StockHelados {
    data:          StockHelado[];
    next_page:     null;
    previous_page: null;
}

export interface StockHelado {
    id:                number;
    unidades:          number;
    codigo_movimiento: string;
    numero_documento:  string;
    fecha_movimiento:  string;
    movimientos_id:    number;
    documento:         string;
    created_at:        string;
    updated_at:        string;
    imagen?:           string;
}


export interface intialStateStockHelado {
    status: boolean;
    StockHelado:StockHelado[];    
    nextPage: string | null;
    prevPage: string | null;
    active: StockHelado | null;
    errorMessage: string | null | undefined;
}
